// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4rDm6tvoYAPYg9Q0cbnmuhlr2A7jtEP4',
    appId: '1:455161491009:web:88955d3a3b99ecd99fa0c0',
    messagingSenderId: '455161491009',
    projectId: 'rayan-b06f7',
    authDomain: 'rayan-b06f7.firebaseapp.com',
    storageBucket: 'rayan-b06f7.firebasestorage.app',
    measurementId: 'G-GXK8CNX3WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfdIWfEK4op0zUVC-tC-lZCAP18cJYw-w',
    appId: '1:455161491009:android:d0e3a8a00fb3d13f9fa0c0',
    messagingSenderId: '455161491009',
    projectId: 'rayan-b06f7',
    storageBucket: 'rayan-b06f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAARnYnyy64oy4Y4s3fS19xlycWdCFa-G0',
    appId: '1:455161491009:ios:0f228555da585aec9fa0c0',
    messagingSenderId: '455161491009',
    projectId: 'rayan-b06f7',
    storageBucket: 'rayan-b06f7.firebasestorage.app',
    iosBundleId: 'com.example.appr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAARnYnyy64oy4Y4s3fS19xlycWdCFa-G0',
    appId: '1:455161491009:ios:0f228555da585aec9fa0c0',
    messagingSenderId: '455161491009',
    projectId: 'rayan-b06f7',
    storageBucket: 'rayan-b06f7.firebasestorage.app',
    iosBundleId: 'com.example.appr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4rDm6tvoYAPYg9Q0cbnmuhlr2A7jtEP4',
    appId: '1:455161491009:web:b4e19b74786374529fa0c0',
    messagingSenderId: '455161491009',
    projectId: 'rayan-b06f7',
    authDomain: 'rayan-b06f7.firebaseapp.com',
    storageBucket: 'rayan-b06f7.firebasestorage.app',
    measurementId: 'G-KF9BVDQB3E',
  );
}
